# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  hello = {
    pname = "hello";
    version = "2.12.1";
    src = fetchurl {
      url = "mirror://gnu/hello/hello-2.12.1.tar.gz";
      sha256 = "sha256-jZkUKv2SV28wsM18tCqNxoCZmLxdYH2Idh9RLibH2yA=";
    };
  };
  ssss = {
    pname = "ssss";
    version = "484620eaa0826c545269e8d25c5762d97baf78df";
    src = fetchFromGitHub {
      owner = "vm-xeck";
      repo = "ssss";
      rev = "484620eaa0826c545269e8d25c5762d97baf78df";
      fetchSubmodules = false;
      sha256 = "sha256-XOLEz8yFORJGKXj8sj2m0A5KgqXObQkfsMSq3kcl684=";
    };
    date = "2022-11-22";
  };
}
