# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  hello = {
    pname = "hello";
    version = "2.12.1";
    src = fetchurl {
      url = "mirror://gnu/hello/hello-2.12.1.tar.gz";
      sha256 = "sha256-jZkUKv2SV28wsM18tCqNxoCZmLxdYH2Idh9RLibH2yA=";
    };
  };
  online-judge-verify-helper = {
    pname = "online-judge-verify-helper";
    version = "c42032627b21f4b1d45a8f42cb9d00dd0fa70668";
    src = fetchFromGitHub {
      owner = "online-judge-tools";
      repo = "verification-helper";
      rev = "c42032627b21f4b1d45a8f42cb9d00dd0fa70668";
      fetchSubmodules = false;
      sha256 = "sha256-Q7uI13kazajeYb3LRK7mMhx0V3hh7CVqnptmQksMLOA=";
    };
    date = "2023-12-09";
  };
  ssss = {
    pname = "ssss";
    version = "484620eaa0826c545269e8d25c5762d97baf78df";
    src = fetchFromGitHub {
      owner = "vm-xeck";
      repo = "ssss";
      rev = "484620eaa0826c545269e8d25c5762d97baf78df";
      fetchSubmodules = false;
      sha256 = "sha256-XOLEz8yFORJGKXj8sj2m0A5KgqXObQkfsMSq3kcl684=";
    };
    date = "2022-11-22";
  };
  vivaldi-ffmpeg-codecs = {
    pname = "vivaldi-ffmpeg-codecs";
    version = "124.0.6367.118";
    src = fetchurl {
      url = "https://api.snapcraft.io/api/v1/snaps/download/XKEcBqPM06H1Z7zGOdG5fbICuf8NWK5R_2843.snap";
      sha256 = "sha256-n/dvqr5jmOlyGNHVpwQD1LTR+UqpZJBRzcB1F8nosSM=";
    };
  };
}
